---
year: '2014'
volume: 39
booktitle: Proceedings of the Sixth Asian Conference on Machine Learning
published: 2015-02-16
shortname: ACML
start: 2014-11-26
end: 2014-11-28
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: acml14
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Dinh
  family: Phung
- given: Hang
  family: Li
description: |
  Proceedings of the Sixth Asian Conference on Machine Learning
    Held in Nha Trang City, Vietnam on 26-28 November 2014

  Published as Volume 39 by the Proceedings of Machine Learning Research on 16 February 2015.

  Volume Edited by:
    Dinh Phung
    Hang Li

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 26--28 Nov
url: http://proceedings.mlr.press
baseurl: "/v39"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v39
bibtex_copy: true
endnote_copy: true
apa_copy: true
email: ''
conference:
  name: Asian Conference on Machine Learning
  url: 
  location: Nha Trang City, Vietnam
  dates:
  - 2014-11-26
  - 2014-11-27
  - 2014-11-28
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v39.bib
